name: Publish

on:
  push:
    branches:
      - master
    paths:
      - charms/**
      - bundle*.yaml

jobs:
  all-bundles:
    name: All Bundles
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install charm --classic
        sudo snap install charmcraft --classic
        sudo snap install juju-helpers --classic --channel edge
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Publish bundle
      env:
        CHARMSTORE_CREDENTIAL: ${{ secrets.CHARMSTORE_CREDENTIAL }}
      run: |
        set -eux
        echo $CHARMSTORE_CREDENTIAL > ~/.go-cookies
        git clone git://git.launchpad.net/canonical-osm
        cp -r canonical-osm/charms/interfaces/juju-relation-mysql mysql
        juju-bundle publish \
            -b bundle.yaml \
            --url cs:~kubeflow-charmers/kubeflow \
            --serial --prune \
            --publish-charms \
            --publish-namespace kubeflow-charmers
        juju-bundle publish -b bundle-lite.yaml --url cs:~kubeflow-charmers/kubeflow-lite
        juju-bundle publish -b bundle-edge.yaml --url cs:~kubeflow-charmers/kubeflow-edge
